# source: https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images#publishing-images-to-github-packages
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ROS_DISTRO: jazzy

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write    
    strategy:
      matrix:
        variant:
          - name: teleop
            platforms: linux/arm64
            context: .
            file: ./docker/Dockerfile-teleop
          - name: ricbot
            platforms: linux/arm64
            context: .
            file: ./docker/Dockerfile-robot
        #   - name: ui
        #     platforms: linux/arm64
        #     context: ./svelte-ui/
        #     file: ./svelte-ui/docker/Dockerfile
        #   - name: ui_com
        #     platforms: linux/arm64
        #     context: ./helloric_ui_com/
        #     file: ./helloric_ui_com/Dockerfile
          - name: ds4
            platforms: linux/arm64
            context: .
            file: ./docker/Dockerfile-ds4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
            submodules: recursive
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # as suggested here:   https://github.com/docker/build-push-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          #  This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/helloric/${{ matrix.variant.name }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest
          labels: |
            labels: |
                org.opencontainers.image.title=HelloRic ${{ matrix.variant.name }}
                org.opencontainers.image.description=Docker image for HelloRic ${{ matrix.variant.name }} node
                org.opencontainers.image.url=https://github.com/helloric/robot-nodes
                org.opencontainers.image.vendor=DFKI RIC
                org.opencontainers.image.licenses=3-Clause BSD License
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see [Usage](https://github.com/docker/build-push-action#usage) in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push ALL Docker images
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.variant.context }}
          file: ${{ matrix.variant.file }}
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.variant.platforms }}
      
      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/helloric/${{ matrix.variant.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
